#!/bin/bash
set -e
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

echo "*** Updating Sources"
apt-get update

echo "*** Prerequisites"
apt-get install git -y
# apt-get upgrade -y

echo "*** Chrome"
cd /tmp
# https://launchpad.net/~osomon/+archive/ubuntu/chromium-dev/
wget https://launchpad.net/~osomon/+archive/ubuntu/chromium-dev/+build/13722974/+files/chromium-browser_64.0.3260.2-0ubuntu0.14.04.1241_armhf.deb -O browser.deb
wget https://launchpad.net/~osomon/+archive/ubuntu/chromium-dev/+build/13722974/+files/chromium-codecs-ffmpeg-extra_64.0.3260.2-0ubuntu0.14.04.1241_armhf.deb -O browser_codec.deb
dpkg -i browser_codec.deb
dpkg -i browser.deb || apt --fix-broken install -y
rm browser*.deb

echo "*** Node"
mkdir -pv /opt/node
curl -L https://nodejs.org/dist/v8.9.4/node-v8.9.4-linux-armv6l.tar.gz | tar xz --strip-components 1 -C /opt/node
ln -sf /opt/node/bin/node /usr/local/bin/node
ln -sf /opt/node/bin/npm /usr/local/bin/npm
/opt/node/bin/npm config set prefix /usr/local

echo "*** Radiodan"
mkdir -p /opt/radiodan
cd /opt/radiodan
git clone https://github.com/andrewn/neue-radio rde
cd rde/manager
npm install --unsafe-perm --production
cd ..
cd physical
JOBS=MAX npm install --unsafe-perm --production # use all cores
cd ..
chown -R pi:pi /opt/radiodan
cp systemd/* /etc/systemd/system/
systemctl daemon-reload
systemctl start manager
systemctl enable manager
systemctl enable manager-web-server
systemctl enable physical

echo "Update complete, please reboot to continue"
